### ISSUE TITLE
Kofta executable symlink

### ISSUE THREAD

**Issue by SamourM** [madhead/kofta#1]
Thanks for this plugin.
Please advise is below link right?

ln -s /usr/libexec/netdata/plugins.d/kofta/gradlew kofta.plugin

as I cannot understand what is /kofta/bin/kofta executable?

**Comment by madhead** [comment]
`kofta/bin/kofta` is a result of building (`./gradlew clean assemble`) this project. It may not be rooter.

**Comment by SamourM** [comment]
Ok fine. now I have kofta/bin/kofta executable, a symlink was created as below:

**kofta.plugin -> /usr/libexec/netdata/plugins.d/kofta/build/distributions/kofta/bin/kofta**


Below is the result when I tried to test the plugin in debug mode:

$ /usr/libexec/netdata/plugins.d/kofta.plugin debug 1 trace kofta
Exception in thread "main" kotlin.KotlinNullPointerException
	at by.dev.madhead.kofta.Kofta.main(kofta.kt:14)

Below is netdata logs:

2019-03-18 07:04:39: netdata INFO  : PLUGINSD[kofta] : thread created with task id 35798
2019-03-18 07:04:39: netdata INFO  : PLUGINSD[kofta] : connected to '/usr/libexec/netdata/plugins.d/kofta.plugin' running on pid 35802
Exception in thread "main" java.io.FileNotFoundException: /etc/netdata/kofta.yml (No such file or directory)
	at by.dev.madhead.kofta.Configuration$Companion.read(Configuration.kt:26)
	at by.dev.madhead.kofta.Kofta.main(kofta.kt:14)
2019-03-18 07:04:40: netdata ERROR : PLUGINSD[kofta] : read failed
2019-03-18 07:04:40: netdata ERROR : PLUGINSD[kofta] : '/usr/libexec/netdata/plugins.d/kofta.plugin' (pid 35802) disconnected after 0 successful data collections (ENDs).
2019-03-18 07:04:40: netdata ERROR : PLUGINSD[kofta] : child pid 35802 exited with code 1.
2019-03-18 07:04:40: netdata ERROR : PLUGINSD[kofta] : '/usr/libexec/netdata/plugins.d/kofta.plugin' (pid 35802) exited with error code 1. Disabling it.
2019-03-18 07:04:40: netdata INFO  : PLUGINSD[kofta] : thread with task id 35798 finished

**Comment by madhead** [comment]
So, it says clearly: you are missing a configuration file `/etc/netdata/kofta.yml`.

**Comment by SamourM** [comment]
Thank you very much. Solved.
